#!/usr/bin/env bash

question=$(echo "lock|logout|reboot|shutdown" | rofi -sep "|" \
    -dmenu -i -p 'System: ' "" -width 20 -hide-scrollbar -font "Ubuntu 8" \
    -eh 1 -line-padding 4 -padding 20 -no-config -lines 4 -theme solarized)

case $question in
    *lock)
        i3lock-fancy
        ;;
    *logout)
        i3-msg exit
        ;;
    *reboot)
        systemctl reboot
        ;;
    *shutdown)
        systemctl poweroff
        ;;
    *)
        exit 0  # do nothing on wrong response
        ;;
esac

